---
title: "306281422_stats101a_project"
author: "Francis Chan"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(tidyverse)
library(car)
imdb<- read_csv("imdb_top_1000.csv")
attach(imdb)
imdb <- imdb[,-c(1,2,4,6,8,10,11,12,13,14)]
imdb
imdb$Runtime <- as.numeric(str_extract(imdb$Runtime, "[0-9]{2,3}"))
imdb$Released_Year <- as.numeric(imdb$Released_Year)

imdb <- imdb[which(!is.na(imdb$Meta_score)),]
imdb <- imdb[which(!is.na(imdb$Gross)),]
imdb <- imdb[which(!is.na(imdb$Released_Year)),]

Released_Year <- imdb$Released_Year
Runtime <- imdb$Runtime
Gross <- imdb$Gross
Meta_score <- imdb$Meta_score
IMDB_Rating <- imdb$IMDB_Rating
No_of_Votes <- imdb$No_of_Votes
```

```{r}
Am1 <- lm(IMDB_Rating ~ Released_Year + Meta_score + No_of_Votes + Gross + Runtime)
summary(Am1)
```

```{r}
model_df <- data.frame(IMDB_Rating, Released_Year, Meta_score, No_of_Votes, Gross, Runtime)
pairs(model_df)
pairs(IMDB_Rating ~ Released_Year + Meta_score + No_of_Votes + Gross + Runtime)
```

```{r}
par(mfrow = c(2,2))
plot(Am1)
```


```{r}
bc <- powerTransform(cbind(IMDB_Rating, Meta_score, No_of_Votes, Released_Year,Gross, Runtime))
summary(bc)
```
```{r}
anova(Am1)
```

```{r}
vif(Am1)
```
```{r}
t_Released_Year <- Released_Year^47
t_Runtime <- Runtime^-0.5
t_Gross <- Gross^0.19
t_Meta_score <- Meta_score^2
t_IMDB_Rating <- IMDB_Rating^-7.6
t_No_of_Votes <- No_of_Votes^0.19

Am2 <- lm(t_IMDB_Rating ~ t_Released_Year + t_Runtime + t_Gross + t_Meta_score + t_No_of_Votes)
summary(Am2)
```
```{r}
anova(Am1, Am2)
```

```{r}
n <- length(Am1$residuals)
backAIC <- step(Am1, direction = "backward", data = imdb)
backBIC <- step(Am1, direction = "backward", k = log(n), data = imdb)
```
```{r}
par(mfrow = c(2,3))
Standard_Residuals <- rstandard(Am1)
plot(Released_Year, Standard_Residuals)
plot(Meta_score, Standard_Residuals)
plot(No_of_Votes, Standard_Residuals)
plot(Gross, Standard_Residuals)
plot(Runtime, Standard_Residuals)
```




